# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Centralink_Function_install.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 850)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 791))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 1111, 281))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.HardWare_info = QtWidgets.QTextBrowser(self.groupBox)
        self.HardWare_info.setGeometry(QtCore.QRect(80, 20, 471, 261))
        self.HardWare_info.setObjectName("HardWare_info")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(560, 30, 72, 241))
        self.label.setObjectName("label")
        self.SoftWare_info = QtWidgets.QTextBrowser(self.groupBox)
        self.SoftWare_info.setGeometry(QtCore.QRect(630, 20, 481, 261))
        self.SoftWare_info.setObjectName("SoftWare_info")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 72, 241))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 290, 1111, 471))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.install = QtWidgets.QPushButton(self.groupBox_2)
        self.install.setGeometry(QtCore.QRect(1010, 430, 93, 28))
        self.install.setObjectName("install")
        self.Cancel = QtWidgets.QPushButton(self.groupBox_2)
        self.Cancel.setGeometry(QtCore.QRect(900, 430, 93, 28))
        self.Cancel.setObjectName("Cancel")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 151, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pre_install_log = QtWidgets.QTextBrowser(self.groupBox_2)
        self.pre_install_log.setGeometry(QtCore.QRect(190, 30, 921, 391))
        self.pre_install_log.setObjectName("pre_install_log")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 0, 1111, 361))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.V_info = QtWidgets.QTextBrowser(self.groupBox_3)
        self.V_info.setGeometry(QtCore.QRect(130, 20, 431, 331))
        self.V_info.setObjectName("V_info")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 72, 321))
        self.label_3.setObjectName("label_3")
        self.Function_Base_info = QtWidgets.QTextBrowser(self.groupBox_3)
        self.Function_Base_info.setGeometry(QtCore.QRect(720, 10, 381, 341))
        self.Function_Base_info.setObjectName("Function_Base_info")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(610, 20, 91, 321))
        self.label_4.setObjectName("label_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 360, 1111, 401))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.Page2_Button_Close = QtWidgets.QPushButton(self.groupBox_4)
        self.Page2_Button_Close.setGeometry(QtCore.QRect(870, 370, 93, 28))
        self.Page2_Button_Close.setObjectName("Page2_Button_Close")
        self.Page2_Button_install = QtWidgets.QPushButton(self.groupBox_4)
        self.Page2_Button_install.setGeometry(QtCore.QRect(990, 370, 93, 28))
        self.Page2_Button_install.setObjectName("Page2_Button_install")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 151, 331))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Page2_Text = QtWidgets.QTextBrowser(self.groupBox_4)
        self.Page2_Text.setGeometry(QtCore.QRect(160, 30, 951, 331))
        self.Page2_Text.setObjectName("Page2_Text")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 1111, 311))
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.Function_A_info = QtWidgets.QTextBrowser(self.groupBox_5)
        self.Function_A_info.setGeometry(QtCore.QRect(0, 20, 1101, 271))
        self.Function_A_info.setObjectName("Function_A_info")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 300, 1091, 451))
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 141, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Page3_Button_Close = QtWidgets.QPushButton(self.groupBox_6)
        self.Page3_Button_Close.setGeometry(QtCore.QRect(890, 410, 93, 28))
        self.Page3_Button_Close.setObjectName("Page3_Button_Close")
        self.Page3_Button_install = QtWidgets.QPushButton(self.groupBox_6)
        self.Page3_Button_install.setGeometry(QtCore.QRect(1000, 410, 93, 28))
        self.Page3_Button_install.setObjectName("Page3_Button_install")
        self.Page3_text = QtWidgets.QTextBrowser(self.groupBox_6)
        self.Page3_text.setGeometry(QtCore.QRect(140, 20, 951, 371))
        self.Page3_text.setObjectName("Page3_text")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Cancel.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Centralink_Function_Install"))
        self.groupBox.setTitle(_translate("MainWindow", "操作系统信息"))
        self.label.setText(_translate("MainWindow", "软件信息"))
        self.label_2.setText(_translate("MainWindow", "硬件信息"))
        self.groupBox_2.setTitle(_translate("MainWindow", "安装选项"))
        self.install.setText(_translate("MainWindow", "Install"))
        self.Cancel.setText(_translate("MainWindow", "Cancel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "预安装软件"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Centralink信息显示"))
        self.label_3.setText(_translate("MainWindow", "版本信息"))
        self.label_4.setText(_translate("MainWindow", "已经部署功能显示"))
        self.groupBox_4.setTitle(_translate("MainWindow", "功能选项"))
        self.Page2_Button_Close.setText(_translate("MainWindow", "退出"))
        self.Page2_Button_install.setText(_translate("MainWindow", "执行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "基础功能"))
        self.groupBox_5.setTitle(_translate("MainWindow", "功能显示"))
        self.groupBox_6.setTitle(_translate("MainWindow", "功能安装"))
        self.Page3_Button_Close.setText(_translate("MainWindow", "退出"))
        self.Page3_Button_install.setText(_translate("MainWindow", "执行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "高级功能"))

